### ISSUE TITLE
Blogposts: Load author images from feed

### ISSUE THREAD

**Issue by k-nut** [okfn/website#318]
The homepage includes a section at the bottom where the three latest blogposts from blog.okfn.org/feed are displayed.

Currently (as of 91a950067ca5b3822fd43674f877a03d35999f20) it only displays the image for `unkown author`. 

It should really display the author's image but that is not in the feed that we get from the wordpress blog. As soon as that is fixed the image should be included here.

The code for this is realized as a custom extension that resides under `foundation/blogfeed`.

**Comment by yotammanor** [comment]
Hi @k-nut , do you know where _can_ I get the image from?

**Comment by yotammanor** [comment]
@morchickit So it seems that in order to get the _gravatar_ image of the writer, the Wordpress that generates the RSS feed needs to add some information (either a link to the author's gravatar directly, or the email of this gravatar). 

As far as I can tell, this info is currently not supplied. Who works on that Blog? Is there someone who works on it on the other side? (Or can/should I?)

**Comment by k-nut** [comment]
In response to your question @yotammanor: Correct, you would need to make sure that that a link to the gravator or the users' names are included in the feed. Which means changing the blogfeed, as far as I can tell there is nothing that you can do from this side of the problem

**Comment by yotammanor** [comment]
@k-nut thanks for the response.

Where is the blogfeed generated, then?

**Comment by k-nut** [comment]
I don't remember. But @pwalsh will know.

**Comment by morchickit** [comment]
All things about the OKI Blog - @gocemitevski is the man.

**Comment by morchickit** [comment]
@yotammanor either open an issue about it here - https://github.com/okfn/wordpress-theme or ask on the #website channel on Slack
