### ISSUE TITLE
Refused to load ... because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by smth** [okfn/website#327]
I'm seeing lots of the following in the console `[Report Only] Refused to load [x] because it violates the following Content Security Policy directive:`

**Comment by k-nut** [comment]
This is because the website is configured to use [Content Security Policy(csp)](https://developer.mozilla.org/en-US/docs/Web/Security/CSP)  to protect against someone maliciously loading code from a third party.

There is a whitelist for domains that are allowed in the settings [here](
https://github.com/okfn/website/blob/master/foundation/settings.py#L365). One would need to add the domains that are currently throwing warnings to their respective lists.

CSP should be used to block requests that are not wanted but is only set up on the website to throw warnings when a request that is not whitelisted is being made. This means that the third party code is still loaded so this should not influence the user's view of the website. It would be good to add those domains to their lists nevertheless and potentially also to set the rules to not only warn but actually block unallowed requests.

**Comment by morchickit** [comment]
@pwalsh do we have any kind list for this on our other websites? Something that I can compare it to?

**Comment by pwalsh** [comment]
@morchickit no. 

@smth what type of contexts does this occur? Development, or general browsing for normal humans?

**Comment by yotammanor** [comment]
@pwalsh to answer your question, the answer is that the console warning happens on both production and dev/staging.

@morchickit to answer your question - the `settings` file does have whitelist of this sorts, it is just not entirely up to date.

I think that adding the particular missing urls to the list is easy enough. If the problem persists, we can try and think of something more clever.

**Comment by hugadams** [comment]
This also happens sporadically when bitbucket has service outages.  Just happened to me and then 5 minutes later

![image](https://user-images.githubusercontent.com/1972276/127887624-f06328af-dccb-49e3-ab8d-6ac1007c3113.png)
