### ISSUE TITLE
Side menu unstyled

### ISSUE THREAD

**Issue by smth** [okfn/website#329]
Side menu on the press resources page is unstyled.

https://okfn.org/press/resources/

**Comment by yotammanor** [comment]
@smth How does it suppose to look like?
(Removing it completely is available through the CMS admin)

**Comment by smth** [comment]
All side menus should look like

![menu](https://cloud.githubusercontent.com/assets/1375708/20263329/187d365c-aa5e-11e6-9d21-19ee41b0b44b.png)

https://okfn.org/about/

**Comment by yotammanor** [comment]
@smth (and @morchickit )

Should it appear like this:
![image](https://cloud.githubusercontent.com/assets/5147457/20309364/5145850a-ab50-11e6-8cc0-adf403498cf4.png)


Or like this:
![image](https://cloud.githubusercontent.com/assets/5147457/20309387/6cc78fa8-ab50-11e6-89bc-58e397da95f8.png)


Note that currently, in order to have the menu display the current "press" location, I had to make Press a descendant of homepage, which also added it to the top navbar. So, there's also the option of adding the one and not the other - But this is the option which I don't know yet how to do (if at all possible). So if you want me to do this, let me know.

**Comment by smth** [comment]
It should be the second one @yotammanor 

Is the issue that the page doesn't currently appear in any menus? I guess if we didn't want it as a top level item, adding it to one of the existing categories would also allow work, right?

**Comment by yotammanor** [comment]
@smth Yes, adding it to a lower descendant of homepage would also work.

Although there was a bug with press/resources regardless of this discussion. I recreated the resource page as a cms_plugin, and once it is deployed, the page should be removed and re-added as a plugin (and then it'll play nicely with the sidebar menu :) )

**Comment by morchickit** [comment]
Can we close this?

**Comment by yotammanor** [comment]
Non until after deployment to production, since it requires a manual change in the Resource page (in particular, adding to the resource page the newly added Resource plugin)

**Comment by yotammanor** [comment]
Done.
