### ISSUE TITLE
Implement multilanguage feature (make the website translatable)

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#898]
We need our website to be accessible in multiple languages. Some of them will receive "official" translations by our team, while others must have some automatic translation feature (via browser, google translate or others).

I'm not sure which is the best solution for our case in Django CMS. I did a quick search and found a few approaches:

[https://docs.django-cms.org/en/latest/how_to/languages.html](https://docs.django-cms.org/en/latest/how_to/languages.html)
[https://github.com/deschler/django-modeltranslation](https://github.com/deschler/django-modeltranslation)
[https://pypi.org/project/google-translate-django4/](https://pypi.org/project/google-translate-django4/)

Which seems more viable?

**Comment by amercader** [comment]
To limit the scope of this issue let's focus on first on providing "static" translations, ie provided by us.
In terms of UI, this should involve:

* a language switcher widget ( en | es | pt links, select input etc), any ideas about placement and design @lucpretti ?
* namespaced URLs for each language using a locale code. No locale defaults to English, eg
    * https://okfn.org/who-we-are/our-team/ (same as https://okfn.org/en/who-we-are/our-team/
    * https://okfn.org/es/who-we-are/our-team/
    * https://okfn.org/pt/who-we-are/our-team/

Internally I assume there will be some sort of Django middleware and models that will allow to store the same content in different languages, and present one or the other based on a global per-request language variable

**Comment by lucpretti** [comment]
-  Re UI, a language switcher has been already developed by Kan as the final top menu item. You can check it [here](https://ishigami.github.io/okfn_front/) (sample below):

![Screenshot 2023-07-12 at 11 55 00](https://github.com/okfn/website/assets/8523847/045d7052-fe86-42de-bee7-df65830ed04c)

- Re URLs, I assume it's possible to update the content slugs as well, right? eg:

https://okfn.org/who-we-are/our-team/ turns into Spanish -> https://okfn.org/es/quienes-somos/equipo/

**Comment by amercader** [comment]
I'm not sure, that's not how CMS handled it out of the box, maybe we can configure some redirects

@pdelboca keep that in mind but consider it a secondary priority

**Comment by pdelboca** [comment]
@lucpretti I have deployed into Staging the feature for translations.

## Preview
[simplescreenrecorder-2023-08-08_09.37.38.webm](https://github.com/okfn/website/assets/6672339/01f8f0dc-8d75-4e99-a1a6-ff39e5b55966)

Please take a look at it, play a little bit a lets start writing down what's missing (like users). I have purposely left out the Language selector since I assume we are gonna need to build the content in PRD before giving access to users to it.

**Comment by lucpretti** [comment]
Great! The preview looks great! I'll play a little bit on staging, but the final content needs to be translated in production once the multilingual thing is deployed.

**Comment by lucpretti** [comment]
The creation of pages and importing/editing content is working fine.

But there's some unexpected behaviours regarding pages management (URLs, hierarchy, menu etc) - I think it's quicker to explain it over a 10 min call.

**Comment by lucpretti** [comment]
I recorded a video trying to reproduce my experience: https://drive.google.com/file/d/1ny2vEQn9Diu-FU1OdWEmN161MFfjWctK/view?usp=sharing

**Comment by lucpretti** [comment]
Ok, so it seems that the language plugin takes into account all parent pages. 

I tried the same in staging and it worked! Pls check:
EN - https://next.okfn.org/en/network/
ES - https://next.okfn.org/es/red-global-open-knowledge/

With that, I think we are ready to deploy to production so I can start working on the proper translations. Anything else before doing that?

**Comment by pdelboca** [comment]
@lucpretti I think we are okay to go as fine detail of what's missing will appear as you work on translations.

This changes will cover 80% of the site so let's start working on translations and we can open new tickets for what's missing.

On the top of my mind:
 - Users description come from the database so I'm sure we will need to do something special for it
 - There will probably be some static content in the site like links/footnotes/etc that will require another bunch of work but let's tackle them in separate issues. If there is something you cannot translate, probably is because it is not an editable plugin yet.

**Comment by lucpretti** [comment]
Sounds good to me! I think this language journey will also help us learn more about how different parts of DjangoCMS work.

Pls let me know once it's deployed to PRD.
