### ISSUE TITLE
Investigation: integrate blog into main okfn.org site

### ISSUE THREAD

**Issue by amercader** [okfn/website#979]
As part of the wider website design refresh we are considering options for blog.okfn.org (#897), currently a separate Wordpress site. These incude updating the Wordpress theme, migrating to an external managed platform or integrating it with the okfn.org Django CMS code base.

The goal of this task is to explore and scope the work need for the Django CMS integration, including the changes needed on the site to create the necessary models and templates and the migration of existing content.

Let's not try to replicate everything currently existing in blog.okfn.org but try to simplify and stick to the new design mockups (frames _NEWS_ and _SINGLE POST_ in Hi-fidelity pages sub-page in the [Figma doc](https://www.figma.com/file/guOb0sWmBtxE5nDXc4MwFb/okfn.org-website?type=design&node-id=1057%3A1217&mode=design&t=QWlCCNWSSJBvv2Ca-1)

- [x] Compile a list of required pages and functionality to replicate in Django (eg Index page with featured post, Single post page with tags, authors, etc)
- [x] Write a short summary of the models that should be written in Django CMS
- [x] List new templates and plugins that we would need, and check which components already exist in HTML/CSS ([here](https://ishigami.github.io/okfn_front/components.html) and [here](https://ishigami.github.io/okfn_front/components-2.html))
- [x] Explore options for migrating existing content, assuming we can use RSS feeds of the current site and/or database dumps. Consider what would be necessary to migrate images as well.

We will need to do a rough estimate of the effort involved but let's investigate what's needed first. Please include anything I haven't considered above.

**Comment by shashigharti** [comment]
Hi @amercader  Here is my time estimation. 

**Django CMS: (5 -6 days)**
- Django App/Plugin.
- Add menu
  - Blog (main menu)
    - All posts (sub menu)
    - Submit guest Post
- UI Pages
  - Main Page (blog.okfn.org)
  - List page (blog.okfn.org/latest)
  - Single Page(blog.okfn.org/2023/09/07/{slug})
  - Submit guest Post(https://blog.okfn.org/submit)
- Features (Components)
  - Search by month(archive)
  - Tag cloud
  - Developer short bio
- Models Required
  - Page
    - Title
    - Description
    - Metadata(seo)
    - Create/Updated Date
  - Author
    - Title
    - Description

**_(Page and author have many-to-many relationship)_**

**To migrate: (2-3 days)**

- Read the page, users and metadata using script(python/php) and write data in the format ready to import in Django CMS.
- Copy the images from wp-content/folders to django images folder.
- Replace the path of images and files in the import sql file wherever necessary.
- Import data to djangocms.

**Testing (2-3 days)**
**Buffer time(2-3 days)**
**SEO**(not sure may be 4-5 days)
  - Link subdomain(blog.okfn.org) to /blog route
    - Should we use the same url format(https://blog.okfn.org/2023/09/07/{slug}/) ?

**Total days(without SEO):** 15
**Total days(with SEO):** 20

Thanks!

**Comment by pdelboca** [comment]
I definitely support the idea of migrating the blog as a Django App. Is what django was built for originally so +1.

I will leave here this link just for reference of other implementations: [https://til.simonwillison.net/django/building-a-blog-in-django](https://til.simonwillison.net/django/building-a-blog-in-django)

@shashigharti regarding your idea:
 - Are you thinking on writting it in DjangoCMS? Or as a new Django app in our project?
 - I think an extra model for Tags would be nice.
 - Let's add a explicit feature for RSS support.
 - How are you planning the content edition? Are you planning to use a WYSIWYG (like TinyMCE or CKEditor)? I think the most "challenging" part is how to handle the format and the static files of the post (like photos and images). As a reference, the blogpost I share uses Markdown for format and I guess he uploads the images to the cloud and then renders it using markdown. We should add a little bit more of meat to this feature.
 - Relating migration, let's see what @lucpretti suggest. He mentioned once that given that all of our content is already indexed, probably is just fine for now to not migrate it. Otherwise, we risk to loose all the SEO already happening.

**Comment by shashigharti** [comment]
@pdelboca 

- I have not fully decided but thinking of using Djangocms plugin.
- Yes, both Tag and RSS support will be an important addition.
- Regarding content edition, I was thinking of using WYSIWYG but I prefer markdown approach. 

For images, may be we could write a plugin or use existing plugin that uploads the image and has simple interface which allows us to copy the image link and use it in blog post. What do you think?

**Comment by lucpretti** [comment]
Closing this one, as we decided to keep the stack the way it is. Thank you all!
