### ISSUE TITLE
People cards are not being pulled in translated pages

### ISSUE THREAD

**Issue by lucpretti** [okfn/website#996]
Some pages on our DjangoCMS install have different layouts. Meaning that parts of that page get automatically pulled from the plugins under "Organisation". Specifically the following:

https://okfn.org/en/who-we-are/our-team/ -> pulls Units and People
https://okfn.org/en/who-we-are/our-board/ -> pulls Boards and People
https://okfn.org/en/network/finland/ (and all other country pages under Network) -> pulls Network groups and People

When those pages get translations, the automatic content disappears. Even when the page uses the same template as the original language.

An example: https://okfn.org/es/quienes-somos/equipo/

Could you please enable automatic content to be displayed in translated pages as well?

**Comment by pdelboca** [comment]
I have been doing some research of our codebase. The way we are currently handling the People data its a little bit messy and over engineered. 

We have structures that aim more to a complex system of managing organizations rather that a simple webpage. Since our People comes from objects in the database we will need to add either new fields for description in different languages or define another way to handle the translation of users.

I will first try to clean a little bit our codebase and come with a proper solution. (example we have `members.html` and `member_details.html`)

**Comment by lucpretti** [comment]
Thank you @pdelboca. Just a quick note that the solution of creating new/duplicated fields for different languages is totally ok in my opinion.

**Comment by pdelboca** [comment]
As a Follow up, I created a new plugin called `card_person` to be able to manage people directly with the CMS.

I suggest the following path @lucpretti :
 - Deploy the plugin to PRD (nothing will change, you will just have a new plugin).
 - We can re-create all the `who-we-are` content under a new URL `about-us`.
 - We switch the menu to point to `about-us` when the work is finished.
 - After that, I can safely clean all the code since it will no longer be needed in PRD.
